/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function diffTwoQoiImages(
  newImage: Buffer,
  oldImage: Buffer,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare const enum QoiChannels {
  Rgb = 3,
  Rgba = 4,
}

export declare function toDitheredGreyImage(
  image: Buffer,
  format?: string | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare function toDitheredGreyWithPngTxt(
  image: Buffer,
  textChunks?: Record<string, string> | undefined | null,
  compressedText?: boolean | undefined | null,
  bestCompression?: boolean | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare function toMonochrome(
  image: Buffer,
  format?: string | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare function toPng(
  image: Buffer,
  textChunks?: Record<string, string> | undefined | null,
  compressedText?: boolean | undefined | null,
  bestCompression?: boolean | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare function toQoi(
  image: Buffer,
  channels?: QoiChannels | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare function toRgbImage(
  image: Buffer,
  format?: string | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export const VERSION: string
