/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function diffTwoImages(
  newImage: Buffer,
  oldImage: Buffer,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare function imageToQoi(
  image: Buffer,
  channels?: QoiChannels | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare const enum QoiChannels {
  Rgb = 3,
  Rgba = 4,
}

export declare function to4Bpp(
  image: Buffer,
  format?: string | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare function to4BppWithTextMetadata(
  image: Buffer,
  textChunks?: Record<string, string> | undefined | null,
  compressedText?: boolean | undefined | null,
  bestCompression?: boolean | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare function toMonochrome(
  image: Buffer,
  format?: string | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare function toRgb4Bpp(
  image: Buffer,
  format?: string | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export declare function toRgb4BppWithTextMetadata(
  image: Buffer,
  textChunks?: Record<string, string> | undefined | null,
  compressedText?: boolean | undefined | null,
  bestCompression?: boolean | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>

export const VERSION: string
