/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function to4Bpp(
  image: Buffer,
  format?: string | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>
export declare function toMonochrome(
  image: Buffer,
  format?: string | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<Buffer>
export const VERSION: string
